global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: postgis/postgis
  tag: "15-3.4"

primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
    readOnlyRootFilesystem: false

  extraEnvVars:
    - name: POSTGRES_DB
      value: "geoface_db"

  persistence:
    enabled: true
    size: "5Gi"
  
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"